In [23]:
from split_mini_boards_functions import *
import pickle

In [24]:
SIZE = 4
AMOUNT_BOARDS = 1000
AMOUNT_MOVES = 100
NUM_DICT = 1
SPLIT_SIZE = 3

In [25]:
gen = 2
name_df = f'{PATH_DF}\\{SIZE}-{AMOUNT_BOARDS}\\{SIZE}size_{AMOUNT_BOARDS}boards_{gen}gen_reverse'
reverse_df = pd.read_pickle(f'{name_df}.pkl')
reverse_df

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10,...,Col_23,Col_24,Col_25,Col_26,Col_27,Col_28,Col_29,Col_30,Col_31,Col_32
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,1,1,1,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,1,0,0
406,1,1,1,0,1,1,0,0,0,0,...,0,1,0,0,1,1,1,0,0,1
407,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,1,1,1,1,1,1
408,1,1,1,1,1,1,1,1,0,0,...,1,0,1,1,0,1,1,1,0,1
409,1,1,1,1,1,1,1,1,0,1,...,1,0,0,1,0,1,0,1,0,1

In [26]:
new_columns = [f'Col_{i}' for i in range(SPLIT_SIZE*SPLIT_SIZE*gen)]
dfs = []
for pixel in range(SIZE*SIZE):
    res_df = pd.DataFrame(columns=new_columns)
    for i, row in reverse_df.iterrows():
        print_big_numbers(i)
        selected_pixels = generate_split_indexes_numbers(SIZE,SPLIT_SIZE,pixel)
        new_row = extract_selected_columns(SIZE, row, selected_pixels)
        res_df = pd.concat([res_df,new_row])
    dfs.append(res_df)

0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400 0
50 100 150 200 250 300 350 400

In [27]:
size = SIZE
amount_boards = AMOUNT_BOARDS
reverse = True
path = PATH_DF
for i in range(len(dfs)):
    os.makedirs(f'{path}\\{size}-{amount_boards}-mini-boards-to-{SPLIT_SIZE}',exist_ok=True)
    if reverse:
        name_df = f'{path}\\{size}-{amount_boards}-mini-boards-to-{SPLIT_SIZE}\\pixel{i}_{size}size_to{SPLIT_SIZE}_{amount_boards}boards_{gen}gen_reverse'
    else:
        name_df = f'{path}\\{size}-{amount_boards}-mini-boards-to-{SPLIT_SIZE}\\pixel{i}_{size}size_to{SPLIT_SIZE}_{amount_boards}boards_{gen}gen_non-reverse'
    dfs[i].to_pickle(f'{name_df}.pkl')

In [28]:
print_boards_from_df_row(reverse_df.iloc[AMOUNT_BOARDS//5],SIZE)

Board 1:
â¬œâ¬œâ¬›â¬›
â¬œâ¬œâ¬›â¬œ
â¬œâ¬›â¬œâ¬›
â¬œâ¬›â¬›â¬œ

Board 2:
â¬œâ¬œâ¬›â¬›
â¬œâ¬œâ¬›â¬œ
â¬›â¬œâ¬›â¬œ
â¬œâ¬œâ¬œâ¬œ

c:\Users\×“×¨×•×¨\PycharmProjects\GameOfLife\split_mini_boards_functions.py:53: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  val = board_values[i * size + j]

In [29]:
center = 0
split_row = extract_selected_columns(SIZE, reverse_df.iloc[AMOUNT_BOARDS//5] ,generate_split_indexes_numbers(SIZE,SPLIT_SIZE,center))
print(generate_split_indexes_numbers(SIZE,SPLIT_SIZE,center))
print_boards_from_df_row(split_row.iloc[0],SPLIT_SIZE)

[15, 12, 13, 3, 0, 1, 7, 4, 5]

Board 1:
â¬œâ¬œâ¬›
â¬›â¬œâ¬œ
â¬œâ¬œâ¬œ

Board 2:
â¬œâ¬œâ¬œ
â¬›â¬œâ¬œ
â¬œâ¬œâ¬œ